language: go

sudo: false

before_script:
  - cd example; find -type f -exec touch -t `date --date=2016-11-21T01:25:30+0800 +%Y%m%d%H%M.%S` {} \;

script:
  - go test -v ./...

os:
  - linux
  - osx

go:
  - 1.4
  - 1.5
  - 1.6
  - tip
