language: go

sudo: false

before_script:
  - TZ=Asia/Hong_Kong find ./example -type f -exec touch -t 201611210125.30 "{}" \;

script:
  - go test -v ./...

os:
  - linux
  - osx

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip
